# Generated by Django 5.0.4 on 2024-04-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('correct_answer', models.IntegerField()),
                ('answer_text', models.CharField(max_length=100)),
                ('num_answers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('question_filename', models.CharField(max_length=255)),
                ('num_questions', models.IntegerField()),
                ('questions_asked', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('percent_correct', models.FloatField()),
                ('elapsed_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superusers', models.TextField(default=dict)),
                ('users', models.TextField(default=dict)),
            ],
        ),
    ]
