# Generated by Django 5.0.4 on 2024-04-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0002_rename_correct_answer_question_correct_answer_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlog',
            name='question_filename',
        ),
    ]
