# Generated by Django 5.0.4 on 2024-04-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0004_quizsession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizSession',
            new_name='Parameters',
        ),
    ]
