# Generated by Django 5.0.4 on 2024-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0005_rename_quizsession_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
    ]
