# Generated by Django 5.0.4 on 2024-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0007_delete_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(default='/users/catherineswope/question.txt', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizlog',
            name='question_file',
            field=models.FileField(default='questions.txt', upload_to=''),
            preserve_default=False,
        ),
    ]
