# Generated by Django 5.0.4 on 2024-04-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0009_questionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz4.questionfile'),
        ),
    ]
