# Generated by Django 5.0.4 on 2024-04-23 19:46

from django.db import migrations
from django.core.files import File

from django.db import migrations

def create_question_file(apps, schema_editor):
    QuestionFile = apps.get_model('quiz4', 'QuestionFile')
    Question = apps.get_model('quiz4', 'Question')

    file_path = '/users/catherineswope/questions1.txt'
    question_file, created = QuestionFile.objects.get_or_create(file=file_path)

    Question.objects.update(question_file=question_file)
class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0010_alter_question_question_file'),
    ]

    operations = [
        migrations.RunPython(create_question_file),
    ]