# Generated by Django 5.0.4 on 2024-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz4', '0011_auto_20240423_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_files/')),
            ],
        ),
    ]
